import React from "react";
import {
  MapContainer,
  TileLayer,
  Marker,
  Popup,
  Polyline,
  Circle,
  CircleMarker,
} from "react-leaflet";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
  BarChart,
  Bar,
} from "recharts";

/**
 * Renders frontend-independent VisualizationSpec generated by FloatChatAI.
 */
export default function VisualizationRenderer({ spec, data, height = 360 }) {
  if (!spec) return null;

  const type = spec.type || "map";
  const title = spec.title || "Visualization";

  // 1. Map Visualization
  if (type === "map") {
    const options = spec.options || {};
    const queryPoint = options.query_point;
    const radiusKm = options.radius_km || 500;

    let center = [15, 65];
    if (queryPoint && queryPoint.latitude !== undefined && queryPoint.longitude !== undefined) {
      center = [queryPoint.latitude, queryPoint.longitude];
    } else if (Array.isArray(data) && data.length > 0 && data[0].latitude) {
      center = [data[0].latitude, data[0].longitude];
    }

    const markers = Array.isArray(data) ? data : data?.results || [];

    return (
      <div className="visualization-container map-vis" style={{ marginTop: "1rem" }}>
        <h4 style={{ marginBottom: "0.5rem", color: "#20ddd8" }}>{title}</h4>
        <div style={{ height: `${height}px`, width: "100%", borderRadius: "8px", overflow: "hidden" }}>
          <MapContainer center={center} zoom={4} style={{ height: "100%", width: "100%" }}>
            <TileLayer
              attribution="&copy; OpenStreetMap contributors"
              url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
            />
            {queryPoint && (
              <Circle
                center={[queryPoint.latitude, queryPoint.longitude]}
                radius={radiusKm * 1000}
                pathOptions={{ color: "#20ddd8", fillColor: "#20ddd8", fillOpacity: 0.1 }}
              >
                <Popup>Query Origin ({queryPoint.latitude}°, {queryPoint.longitude}°)</Popup>
              </Circle>
            )}
            {markers.map((item, idx) => {
              const lat = item.latitude ?? item.last_location?.latitude;
              const lon = item.longitude ?? item.last_location?.longitude;
              const id = item.float_id || item.id || `Float #${idx + 1}`;
              if (lat === undefined || lon === undefined) return null;
              return (
                <Marker key={idx} position={[lat, lon]}>
                  <Popup>
                    <strong>{id}</strong>
                    <br />
                    Lat: {lat}°, Lon: {lon}°
                    {item.distance_km && <><br />Distance: {item.distance_km.toFixed(1)} km</>}
                  </Popup>
                </Marker>
              );
            })}
          </MapContainer>
        </div>
      </div>
    );
  }

  // 2. Trajectory Map
  if (type === "trajectory_map" || type === "trajectory") {
    const rawPoints = Array.isArray(data) ? data : data?.trajectory || [];
    const positions = rawPoints.map((pt) => [pt.latitude, pt.longitude]);
    const center = positions.length > 0 ? positions[positions.length - 1] : [10, 60];

    return (
      <div className="visualization-container trajectory-vis" style={{ marginTop: "1rem" }}>
        <h4 style={{ marginBottom: "0.5rem", color: "#20ddd8" }}>{title}</h4>
        <div style={{ height: `${height}px`, width: "100%", borderRadius: "8px", overflow: "hidden" }}>
          <MapContainer center={center} zoom={5} style={{ height: "100%", width: "100%" }}>
            <TileLayer
              attribution="&copy; OpenStreetMap contributors"
              url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
            />
            <Polyline positions={positions} pathOptions={{ color: "#20ddd8", weight: 3, dashArray: "6 6" }} />
            {positions.map((pos, idx) => (
              <CircleMarker
                key={idx}
                center={pos}
                radius={idx === positions.length - 1 ? 8 : 4}
                pathOptions={{
                  color: "#20ddd8",
                  fillColor: idx === positions.length - 1 ? "#20ddd8" : "#061428",
                  fillOpacity: 1,
                }}
              >
                <Popup>Cycle fix {idx + 1}: [{pos[0]}°, {pos[1]}°]</Popup>
              </CircleMarker>
            ))}
          </MapContainer>
        </div>
      </div>
    );
  }

  // 3. Profile Chart (Vertical Depth vs Parameter)
  if (type === "profile_chart" || type === "profile") {
    const rawItems = Array.isArray(data) ? data : data?.measurements || [];
    const chartData = rawItems.map((m) => ({
      depth: m.depth_m ?? m.pressure_dbar ?? 0,
      temperature: m.temperature_C ?? m.parameters?.temperature_C,
      salinity: m.salinity ?? m.parameters?.salinity,
    })).filter((m) => m.temperature !== undefined || m.salinity !== undefined);

    const xParam = spec.x_axis || "temperature";

    return (
      <div className="visualization-container profile-vis" style={{ marginTop: "1rem" }}>
        <h4 style={{ marginBottom: "0.5rem", color: "#20ddd8" }}>{title}</h4>
        <div style={{ height: `${height}px`, width: "100%" }}>
          <ResponsiveContainer width="100%" height="100%">
            <LineChart data={chartData} layout="vertical" margin={{ top: 10, right: 30, left: 10, bottom: 10 }}>
              <CartesianGrid stroke="#173149" strokeDasharray="3 3" />
              <XAxis type="number" stroke="#9fb3c1" />
              <YAxis dataKey="depth" type="number" reversed stroke="#9fb3c1" label={{ value: "Depth (m)", angle: -90, position: "insideLeft" }} />
              <Tooltip />
              <Legend />
              {xParam.includes("sal") ? (
                <Line type="monotone" dataKey="salinity" stroke="#9fb7ff" strokeWidth={2} dot={{ r: 3 }} name="Salinity (PSU)" />
              ) : (
                <Line type="monotone" dataKey="temperature" stroke="#20ddd8" strokeWidth={2} dot={{ r: 3 }} name="Temperature (°C)" />
              )}
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>
    );
  }

  // 4. Statistics or Comparison Chart
  if (type === "statistics" || type === "comparison_chart" || type === "comparison") {
    const params = data?.parameters || [];
    return (
      <div className="visualization-container stats-vis" style={{ marginTop: "1rem" }}>
        <h4 style={{ marginBottom: "0.5rem", color: "#20ddd8" }}>{title}</h4>
        {params.length > 0 ? (
          <div style={{ height: `${height}px`, width: "100%" }}>
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={params} margin={{ top: 10, right: 30, left: 10, bottom: 10 }}>
                <CartesianGrid stroke="#173149" strokeDasharray="3 3" />
                <XAxis dataKey="name" stroke="#9fb3c1" />
                <YAxis stroke="#9fb3c1" />
                <Tooltip />
                <Legend />
                <Bar dataKey="mean" fill="#20ddd8" name="Mean Value" />
                <Bar dataKey="min" fill="#9fb7ff" name="Min Value" />
                <Bar dataKey="max" fill="#f59e0b" name="Max Value" />
              </BarChart>
            </ResponsiveContainer>
          </div>
        ) : (
          <p style={{ color: "#9fb3c1" }}>Statistical summary metrics processed.</p>
        )}
      </div>
    );
  }

  // 5. Table Fallback
  return (
    <div className="visualization-container table-vis" style={{ marginTop: "1rem" }}>
      <h4 style={{ marginBottom: "0.5rem", color: "#20ddd8" }}>{title}</h4>
      <div style={{ maxHeight: `${height}px`, overflowY: "auto" }}>
        <table style={{ width: "100%", fontSize: "0.85rem", borderCollapse: "collapse" }}>
          <thead>
            <tr style={{ background: "#0a192f", color: "#20ddd8" }}>
              <th style={{ padding: "6px" }}>Float ID</th>
              <th style={{ padding: "6px" }}>Location</th>
              <th style={{ padding: "6px" }}>Details</th>
            </tr>
          </thead>
          <tbody>
            {(Array.isArray(data) ? data : data?.results || []).map((row, i) => (
              <tr key={i} style={{ borderBottom: "1px solid #173149" }}>
                <td style={{ padding: "6px" }}>{row.float_id || row.id || `#${i + 1}`}</td>
                <td style={{ padding: "6px" }}>{row.latitude ?? "—"}°, {row.longitude ?? "—"}°</td>
                <td style={{ padding: "6px" }}>{row.distance_km ? `${row.distance_km.toFixed(1)} km` : (row.region || "—")}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
