from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class SpatialBoundingBox(BaseModel):
    min_lat: float = Field(..., ge=-90.0, le=90.0)
    max_lat: float = Field(..., ge=-90.0, le=90.0)
    min_lon: float = Field(..., ge=-180.0, le=180.0)
    max_lon: float = Field(..., ge=-180.0, le=180.0)


class QueryRequest(BaseModel):
    """
    Flexible multi-criteria search request.
    Supports deterministic filtering and is designed to accept
    parsed query AST or structured JSON generated by the future AI layer.
    """
    float_ids: Optional[List[str]] = Field(None, description="Specific float IDs")
    bounding_box: Optional[SpatialBoundingBox] = Field(None, description="Spatial bounding box")
    start_date: Optional[datetime] = Field(None, description="Start date filter")
    end_date: Optional[datetime] = Field(None, description="End date filter")
    parameters: Optional[List[str]] = Field(None, description="Requested physical/BGC parameters")
    depth_range: Optional[Dict[str, float]] = Field(None, description="Min/max depth in meters")
    
    # Optional field reserved for AI-generated query metadata / natural language text
    natural_language_prompt: Optional[str] = Field(
        None,
        description="Optional natural language query forwarded from/to future AI layer"
    )
    limit: Optional[int] = Field(50, ge=1, le=1000)
    offset: Optional[int] = Field(0, ge=0)


class QueryResponse(BaseModel):
    """Response envelope for custom queries."""
    total_matched: int = 0
    returned_count: int = 0
    limit: Optional[int] = None
    offset: Optional[int] = None
    data: List[Dict[str, Any]] = Field(default_factory=list)
    query_executed: Dict[str, Any] = Field(default_factory=dict)
    ai_context: Optional[Dict[str, Any]] = Field(
        None,
        description="Reserved context for future AI layer integration"
    )

